### ISSUE TITLE
Unable to pair sphero using 'gort bluetooth pair'

### ISSUE THREAD

**Issue by solojavier** [hybridgroup/gort#2]
When I ran:

```
$ gort bluetooth pair 00:06:66:44:39:C6
```

I got this message:

```
RequestPinCode (/org/bluez/427/hci0/dev_00_06_66_44_39_C6)
Enter PIN Code: Enter PIN Code: Creating device failed: org.bluez.Error.AuthenticationRejected: Authentication Rejected
```

I was not able to enter a PIN Code, it just returned that error...

When I used:

```
bluez-simple-agent hci0 00:06:66:44:39:C6
```

I was able to enter the PIN Code 1234 and pair succesfully...

**Comment by dpritchett** [comment]
Thanks for the workaround @solojavier :)

**Comment by deadprogram** [comment]
Gort has no longer been using these particular commands "under the hood" for a while. Closing, please open new issues with any troubles you might have.
