### ISSUE TITLE
Missing library from Gort OS X build

### ISSUE THREAD

**Issue by juliancheal** [hybridgroup/gort#33]
Using the latest build of Gort (0.3.0) on OS X (10.9.5) with Go version 1.4.2. Gort is missing "Current"

~ $ go version
go version go1.4.2 darwin/amd64
~ $ gort -v
gort version 0.3.0
~ $ gort dronedrop install
2015/02/28 14:17:56 Pushing dronedrop...
2015/02/28 14:17:56 user: Current not implemented on darwin/amd64

**Comment by deadprogram** [comment]
The reason for this is http://stackoverflow.com/questions/20609415/cross-compiling-user-current-not-implemented-on-linux-amd64

The solution is we need to do the cross-compiling on an OSX machine.

We should add something to README to warn people about this (including ourselves).
