### ISSUE TITLE
Unable to upload firmata to arduino duemilanove

### ISSUE THREAD

**Issue by razasayed** [hybridgroup/gort#34]
I have a arduino duemilanove, and im unable to upload firmata to the board using gort on my OSX machine . Im however able to upload firmata to the board using the arduino ide. 
I tried doing ```gort arduino upload firmata /dev/cu.usbserial-A700fmBa``` and also ```gort arduino upload firmata /dev/tty.usbserial-A700fmBa```.In both the cases i get the error ```avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x86```.
Any way to fix this ?

Thanks.

**Comment by deadprogram** [comment]
The new 0.5.2 release of Gort is now out, and should address this issue. Please reopen if you need further assistance, or open a new issue. Thanks!
