### ISSUE TITLE
gort not detected MAC

### ISSUE THREAD

**Issue by lucjands** [hybridgroup/gort#36]
When trying to use gort I get following message
~~~
Lucjans-MacBook-Air:robots lds$ gort scan serial
-bash: gort: command not found
~~~
Is there a way to solve this problem?

**Comment by Jesterovskiy** [comment]
Run it from folder, that you downloaded: `./gort scan serial`

**Comment by deadprogram** [comment]
We now have a Homebrew base install for OSX. I am closing this, please reopen if needed.
