### ISSUE TITLE
Arduino Mega ADK: Is compatible with Gort?

### ISSUE THREAD

**Issue by nmarmon** [hybridgroup/gort#40]
Hi,

I have problems when I try to upload firmata inside my arduino Mega ADK. When I try to upload firmata to my board, like this (in Linuxmint):

$ sudo gort arduino upload firmata /dev/ttyACM0

It shows the next error message:

avrdude: stk500_recv(): programmer is not responding

When I see this error in Arduino IDE, the solution was change the board in the corresponding menu. But in Gort, how I can change the board type? Or is it simply that Mega ADK is incompatible with Gort? Thanks for your answers. All of them are welcome.

**Comment by deadprogram** [comment]
The new 0.5.2 release of Gort is now out, and should address this issue. Please reopen if you need further assistance, or open a new issue. Thanks!
