### ISSUE TITLE
gort arduino firmata relay on by default

### ISSUE THREAD

**Issue by JesusIslam** [hybridgroup/gort#42]
After I uploaded the firmata firmware to my UNO, everytime I power it up, the normally opened relay always got turned on immidiately. 

How can I make it so it won't turned on immidiately (off by default)? Should I make custom firmata firmware? If so, how do I do that?

Thanks.

**Comment by deadprogram** [comment]
Hi @JesusIslam 

When the Arduino is first booting up before the firmware loads, you cannot count on the pins being in a consistent state. Normally the circuit you would wire up would accommodate this. For example:

![Relay circuit](http://www.electroschematics.com/wp-content/uploads/2013/07/arduino-control-relay-schematic.png)

From this useful post:

http://www.electroschematics.com/8975/arduino-control-relay/

Hope that helps!

**Comment by deadprogram** [comment]
Hi, @JesusIslam did you get your problem resolved? If you still need further assistance, please reopen this issue. Thanks!
