### ISSUE TITLE
gort arduino upload firmata fails

### ISSUE THREAD

**Issue by Rinma21** [hybridgroup/gort#43]
When i try to run `gort arduino upload firmata /dev/ttyACM0` on antergos i get this error message:

```
signal: floating point exception (core dumped)
```

i use an arduino uno r3 smd

**Comment by deadprogram** [comment]
Hi @Rinma21 sorry I just noticed this issue, something wrong with my notifications.

In any case, did you find a solution to your problem? I have not tested gort on any arch distros myself.

**Comment by deadprogram** [comment]
Closing due to age of issue. Please reopen if needed. Thanks.
