### ISSUE TITLE
There are lots of versions of firmata out there, which one is it that gort uploads?

### ISSUE THREAD

**Issue by troywweber7** [hybridgroup/gort#46]

**Comment by deadprogram** [comment]
Hi @troywweber7 it is StandardFirmata.

Hope that helps!

**Comment by troywweber7** [comment]
Thank you, that resolves it @deadprogram.

Additionally I'm looking to extend Cylon functionality to include the ability to drive stepper motors. I have a sense that this may involve me adding support for other firmatas on cylon-firmata or at the very least extending the cylon-gpio module. I'm seeking direction on one or both of those tasks [here](https://github.com/hybridgroup/cylon-firmata/issues/47) and [here](https://github.com/hybridgroup/cylon-gpio/issues/55). I apologize for the duplicates. I might also be interested to help add support to gort to easily upload alternative firmatas.

**Comment by deadprogram** [comment]
Hi @troywweber7 a contribution that allowed for uploading other Firmata versions would be greatly appreciated.
