### ISSUE TITLE
Upload hexfile to Digispark ATTiny85

### ISSUE THREAD

**Issue by gurre** [hybridgroup/gort#57]
Does the tool support the device Digispark ATTiny85 for uploading firmware?

**Comment by deadprogram** [comment]
Hello @gurre perhaps you are looking for the `gort digispark` command?

**Comment by gurre** [comment]
Well I had a strange issues with avrdude and Arduino and eventually couldn't use it.

I [used](https://gist.github.com/gurre/20441945fdcbb0c2f2c346d9f894a361) Gort for installing micronucleus though. Worked like a charm!

Ended up uploading the code using `micronucleus --run Blink.hex/Blink.hex.ino.tiny8.hex`
