### ISSUE TITLE
Website not available

### ISSUE THREAD

**Issue by ghost** [hybridgroup/gort#62]
Hello since a few days ago the official page (http://gort.io/) is not available. Linux installers that are downloaded by curl, are damaged and can not be installed correctly. 
@deadprogram @zankich @edgarsilva @hunterboerner @rafmagana @erkkah

**Comment by deadprogram** [comment]
Thanks for letting us know. Site is back up with new download locations on Github.

**Comment by ghost** [comment]
Well, it's already working. Thank you.
